### ISSUE TITLE
Installing with a release name other than `besu` does not work

### ISSUE THREAD

**Issue by marcelloromani** [PegaSysEng/besu-kubernetes#33]
This is due to some resources having a hard-coded name.

Example:

The validator configmap name is built from the release name:

https://github.com/PegaSysEng/besu-kubernetes/blob/master/helm/ibft2/besu/templates/validators-configmap.yaml#L4

```
metadata:
  name: {{ template "besu.fullname" . }}-validators-configmap
```

but it is referenced as a hard-coded value:

https://github.com/PegaSysEng/besu-kubernetes/blob/master/helm/ibft2/besu/templates/validator1-statefulset.yaml#L93

```
          - name: VALIDATOR1_PUBKEY
            valueFrom:
              configMapKeyRef:
                name: besu-validators-configmap
                key: validator1PubKey
```
