### ISSUE TITLE
kubernetes liveness and readiness checks fail due to error {"message":"Host not authorized."}

### ISSUE THREAD

**Issue by e-nikolov** [PegaSysEng/besu-kubernetes#38]
I think that kubernetes does those checks by performing an http request to the IP of the pod, but the host it does it from isn't white-listed by the besu node, so it returns an error.

**Comment by joshuafernandes** [comment]
Thank you for raising this. Could you please tell us:
- how you have your cluster setup
- how you read these logs
- how we reproduce this 

The 'host not authorized' message from Besu generally stems from the config.toml have specific values for host-whitelist where its restricted. https://besu.hyperledger.org/en/stable/HowTo/Troubleshoot/Troubleshooting/

**Comment by e-nikolov** [comment]
The setup is a slightly modified version of the one [here](https://github.com/PegaSysEng/besu-kubernetes/tree/master/kubectl/ethash)

I have only 1 besu node running using this command:
```
/opt/besu/bin/besu \
                --network=ropsten \
                --data-path=/opt/besu/data \
                --sync-mode=FULL \
                --rpc-http-enabled \
                --rpc-http-host=0.0.0.0 \
                --rpc-http-port=8545 \
                --rpc-http-cors-origins=${NODES_HTTP_CORS_ORIGINS} \
                --rpc-ws-enabled \
                --rpc-ws-host=0.0.0.0 \
                --rpc-ws-port=8546 \
                --metrics-enabled=true \
                --metrics-host=0.0.0.0 \
                --metrics-port=9545 \
```
It is using this config map: 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: besu-configmap
  labels:
    app: besu-configmap
data:
  nodesHttpCorsOrigins: "*"
  nodesHostWhitelist: "*"
```
The whitelist seems to be set to *.

I actually got it to work today by setting the Host http header of the health probes to "localhost", but I'm not sure if that's a good solution.

```
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: localhost
              path: /liveness
              port: 8545
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: localhost
              path: /readiness
              port: 8545
            initialDelaySeconds: 600
            failureThreshold: 10
            periodSeconds: 60
```

I saw the log via kubectl describe on the pod.
